name = "valorwaveentertainment"
main = "_worker.js"
compatibility_date = "2024-10-01"

# REQUIRED for Cloudflare Pages
pages_build_output_dir = "/"

[assets]
directory = "/"
binding = "STATIC"   # <-- MUST NOT be ASSETS
