name = "valorwaveentertainment"
main = "_worker.js"
compatibility_date = "2024-01-01"

[vars]
GITHUB_OWNER = "sammassengale82"
GITHUB_REPO = "valorwaveentertainment"
GITHUB_BRANCH = "main"
GITHUB_CLIENT_ID = "Ov23liB8LRnUd7aQcwyZ"
GITHUB_REDIRECT_URI = "https://valorwaveentertainment.com/cms/callback"
