name: Fetch Static CMS

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download Static CMS App UMD build
        run: |
          mkdir -p src/admin/cms
          curl -L "https://unpkg.com/@staticcms/app@1.0.0/dist/static-cms-app.js" -o src/admin/cms/static-cms-app.js

      - name: Commit file
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add src/admin/cms/static-cms-app.js
          git commit -m "Fetch correct Static CMS App UMD build" || echo "No changes to commit"
          git push
